'use client';

// The four cards at the top of the dashboard (/app).
//
// 2026-10-08 — rebuilt on the owner's Iconly reference (four service cards:
// red, white, white, blue): a two-line title — the figure in full colour, what
// it counts in a softer tint under it —, an arrow tile with an uppercase link
// at the bottom, and a 3D object filling the right of the card. The colours are
// sampled from that image: red #F34857 → #EF3E50 with a pink glow top-right,
// blue #435CFE → #2948FC with a pale-blue glow, white on the grey page ground.
// No border on any of them: they stand out by their fill, as in the reference.
// One row of four on a computer (from 1280px), 2 × 2 below — the owner's layout —
// and always wider than tall, so the object has room (owner: "trop carrées").
//
// The objects are architectural (towers, a bridge, a crane, a rolled plan),
// generated by the owner on 2026-10-08 on a ground of the card's colour. The
// files in /public/dashboard are cropped to the object's side, compressed to
// WebP and their ground colour-matched to the card (red 242/65/75, blue
// 39/69/252); the left edge of each fades into the card, so no seam shows.
//
// Every figure comes from the database on the server (projects-data.ts) —
// nothing is estimated, projected or padded.
import Link from 'next/link';
import { useLocale, useTranslations } from '@/lib/i18n/LocaleContext';
import type { PricingTierId } from '@/lib/pricing-tiers';

export interface DashboardData {
  projectCount: number;
  renderCount: number;
  /** ISO date of the most recent render, or null when nothing has been generated. */
  lastActivityAt: string | null;
  tier: PricingTierId | null;
  /** Monthly allowance, null when no plan is active. */
  quotaMax: number | null;
  /** Generations left in the current period, null when no plan is active. */
  quotaRemaining: number | null;
  /** ISO date the current period ends, null when no plan is active. */
  periodEndsAt: string | null;
}

type Tone = 'red' | 'white' | 'blue';

/** Card ground, title tints and arrow tile per tone — complete class strings
 *  so Tailwind's scanner sees them (see CLAUDE.md, JIT gotcha). */
const TONE: Record<Tone, { card: string; title: string; sub: string; tile: string; link: string }> =
  {
    red: {
      card: 'bg-[radial-gradient(120%_90%_at_100%_0%,#F88B98_0%,rgba(248,139,152,0)_55%),linear-gradient(135deg,#F34857_0%,#EF3E50_60%,#F25061_100%)]',
      title: 'text-white',
      sub: 'text-[#FFD0D6]',
      tile: 'bg-white text-[#17161F]',
      link: 'text-white',
    },
    white: {
      card: 'bg-white',
      title: 'text-[#111111]',
      sub: 'text-[#9B9B9B]',
      tile: 'bg-[#111111] text-white',
      link: 'text-[#111111]',
    },
    blue: {
      card: 'bg-[radial-gradient(110%_100%_at_100%_0%,#A3C2FB_0%,rgba(163,194,251,0)_55%),linear-gradient(135deg,#435CFE_0%,#2948FC_60%,#3550FB_100%)]',
      title: 'text-white',
      sub: 'text-[#B9C6FF]',
      tile: 'bg-white text-[#2948FC]',
      link: 'text-white',
    },
  };

interface CardArt {
  src: string;
  /** Which part of the picture stays in view when the card crops it. */
  position: string;
}

/** The 3D object on each card, from /public/dashboard. */
const CARD_ART: Record<'projects' | 'renders' | 'activity' | 'quota', CardArt> = {
  projects: { src: '/dashboard/tours.webp', position: 'object-[100%_55%]' }, // red — white towers
  renders: { src: '/dashboard/pont.webp', position: 'object-[100%_70%]' }, // white — a black bridge
  activity: { src: '/dashboard/grue.webp', position: 'object-[80%_20%]' }, // white — a tower crane
  quota: { src: '/dashboard/plan.webp', position: 'object-[100%_55%]' }, // blue — a rolled plan
};

function ArrowTile({ className }: { className: string }) {
  return (
    <span
      aria-hidden
      className={`flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg ${className}`}
    >
      <svg
        viewBox="0 0 24 24"
        width="13"
        height="13"
        fill="none"
        stroke="currentColor"
        strokeWidth="2.4"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M7 17 17 7M9 7h8v8" />
      </svg>
    </span>
  );
}

function ServiceCard({
  tone,
  title,
  sub,
  linkLabel,
  href,
  art,
}: {
  tone: Tone;
  title: string;
  sub: string;
  linkLabel: string;
  href: string;
  art: CardArt;
}) {
  const t = TONE[tone];
  return (
    <Link
      href={href}
      className={`group relative flex min-h-[150px] flex-col justify-between overflow-hidden rounded-[20px] p-4 transition-transform duration-200 ease-out motion-safe:hover:-translate-y-0.5 min-[640px]:h-[200px] min-[640px]:p-7 min-[1280px]:aspect-[8/5] min-[1280px]:h-auto min-[1280px]:min-h-[160px] min-[1280px]:p-5 ${t.card}`}
    >
      {/* The object fills the right of the card; its left edge melts into the
          card's colour, so the text column beside it stays on a plain ground. */}
      <img
        src={art.src}
        alt=""
        aria-hidden
        draggable={false}
        className={`pointer-events-none absolute inset-y-0 right-0 h-full w-[52%] object-cover [mask-image:linear-gradient(to_right,transparent_0%,#000_42%)] transition-transform duration-300 ease-out motion-safe:group-hover:scale-[1.03] min-[640px]:w-[55%] ${art.position}`}
      />
      <div className="relative max-w-[64%] min-[640px]:max-w-[52%] min-[1280px]:max-w-[56%]">
        <div
          className={`font-[family-name:var(--font-display)] text-[18px] font-semibold leading-[1.15] tracking-tight min-[640px]:text-[28px] min-[1280px]:text-[20px] ${t.title}`}
        >
          {title}
        </div>
        <div
          className={`font-[family-name:var(--font-display)] text-[13px] font-semibold leading-[1.2] tracking-tight min-[640px]:text-[22px] min-[1280px]:text-[15px] ${t.sub}`}
        >
          {sub}
        </div>
      </div>
      <div className="relative mt-3 flex max-w-[64%] items-center gap-2.5 min-[640px]:max-w-[60%]">
        <ArrowTile className={t.tile} />
        <span
          className={`text-[10px] font-medium uppercase leading-tight tracking-[0.03em] min-[640px]:text-[13px] min-[1280px]:text-[11px] ${t.link}`}
        >
          {linkLabel}
        </span>
      </div>
    </Link>
  );
}

export function DashboardStats({ data }: { data: DashboardData }) {
  const t = useTranslations();
  const { locale } = useLocale();
  const intl = locale === 'fr' ? 'fr-FR' : 'en-US';
  const shortDate = (iso: string) =>
    new Date(iso).toLocaleDateString(intl, { day: 'numeric', month: 'short' });

  const hasPlan = data.tier !== null && data.quotaMax !== null && data.quotaRemaining !== null;
  const n = (v: number) => v.toLocaleString(intl);

  return (
    <div className="grid grid-cols-2 gap-2.5 min-[640px]:gap-4 min-[1280px]:grid-cols-4">
      <ServiceCard
        tone="red"
        title={t('dashboard.cardProjectsTitle', { count: n(data.projectCount) })}
        sub={t('dashboard.cardProjectsSub')}
        linkLabel={t('dashboard.cardProjectsLink')}
        href="/app/projets"
        art={CARD_ART.projects}
      />
      <ServiceCard
        tone="white"
        title={t('dashboard.cardRendersTitle', { count: n(data.renderCount) })}
        sub={t('dashboard.cardRendersSub')}
        linkLabel={t('dashboard.cardRendersLink')}
        href="/app/generer"
        art={CARD_ART.renders}
      />
      <ServiceCard
        tone="white"
        title={
          data.lastActivityAt
            ? shortDate(data.lastActivityAt)
            : t('dashboard.cardActivityNoneTitle')
        }
        sub={data.lastActivityAt ? t('dashboard.cardActivitySub') : t('dashboard.cardActivityNone')}
        linkLabel={t('dashboard.cardActivityLink')}
        href={data.lastActivityAt ? '/app/projets' : '/app/generer'}
        art={CARD_ART.activity}
      />
      {/* What is left of the plan; it opens the subscription page. */}
      <ServiceCard
        tone="blue"
        title={
          hasPlan
            ? t('dashboard.cardQuotaTitle', { count: n(data.quotaRemaining!) })
            : t('dashboard.noTierTitle')
        }
        sub={
          hasPlan
            ? data.periodEndsAt
              ? t('dashboard.cardQuotaSubDate', { date: shortDate(data.periodEndsAt) })
              : t('dashboard.cardQuotaSub')
            : t('dashboard.cardQuotaNone')
        }
        linkLabel={t('dashboard.cardQuotaLink')}
        href="/app/tarifs"
        art={CARD_ART.quota}
      />
    </div>
  );
}
