'use client';

// The one app rail, mounted once by AppChrome and kept across navigations:
// dashboard, projects, generation space, every in-app page AND the open
// project workspace (whose render tree is portalled into `treeSlotRef`).
// No link to /admin here, ever — the admin back-office is a fully separate
// space reached by typing the URL directly, never surfaced from this sidebar.
//
// 2026-10-08 — rebuilt on the owner's "Shopall" reference: a floating white
// card on the grey ground, from top to bottom
//   the fold button, then the RenderBox name (the owner's logo goes there)
//   Général   — Accueil, Mes images, Image, Enhance
//   Aide      — Info, Assistant
//   (a project's render tree, when one is open)
//   Profil    — Paramètres, Abonnement, Se déconnecter
//   the account — initials, name, a chevron → Paramètres
// each section split from the next by a full-width hairline. (A "Formule"
// plan selector sat under the logo for a few hours; the owner removed it —
// the plan and renders left are in the header pill and on Abonnement.) Folded (76px),
// the captions stay, centred, and every entry is a 44px rounded square.
import Link from 'next/link';
import { ChevronDown } from 'react-iconly';
import { PanelToggleIcon } from './PanelToggleIcon';
import { openAssistant } from './AssistantWidget';
import { useAuth } from '@/contexts/AuthContext';
import { useTranslations } from '@/lib/i18n/LocaleContext';
import { isPlaceholderAccount } from '@/lib/account-label';
import { NavPendingIcon } from './NavPending';
import { RailIcon, type RailIconName } from './RailIcon';
import type { AppMode } from './CommandBar';
import {
  ICON_ACTIVE,
  ICON_IDLE,
  RAIL_CAPTION,
  RAIL_TOGGLE,
  ROW,
  ROW_ACTIVE,
  ROW_IDLE,
  ROW_ROUND,
  ROW_WIDE,
} from './nav-row';

/**
 * Which rail entry is the page you are on. AppChrome derives it from the URL
 * (see railPageFor), and marks a clicked entry at once, before its page
 * arrives.
 */
export type RailPage =
  | 'dashboard'
  | 'images'
  | 'generate'
  | 'enhance'
  | 'pricing'
  | 'settings'
  | 'info';

/** A section: full-width hairline above, its own padding. */
const SECTION = 'border-t border-[#ECECF2]';

// The rail's entries wear app-icon tiles since 2026-10-08 (owner, after
// Krea's sidebar): glossy rounded squares in the charter's blues and red,
// generated by the owner from one sheet so they match, cropped and exported
// at 72px (3× the 24px they show at) in /public/rail. The images carry white
// corners; the rounding here clips them. Se déconnecter has its own tile
// (red, a door and an arrow), from a second sheet.
const RAIL_TILES: Partial<Record<RailIconName, string>> = {
  dashboard: '/rail/accueil.webp',
  projects: '/rail/images.webp',
  image: '/rail/image.webp',
  enhance: '/rail/enhance.webp',
  info: '/rail/info.webp',
  settings: '/rail/parametres.webp',
  pricing: '/rail/abonnement.webp',
};

function RailTile({ src }: { src: string }) {
  return (
    <img
      src={src}
      alt=""
      aria-hidden
      width={24}
      height={24}
      draggable={false}
      className="h-6 w-6 flex-shrink-0 rounded-[7px] shadow-[0_2px_5px_-2px_rgba(23,22,31,0.35)]"
    />
  );
}

function RailLink({
  href,
  label,
  icon,
  active,
  collapsed,
  onNavigate,
}: {
  href: string;
  label: string;
  icon: RailIconName;
  active: boolean;
  collapsed: boolean;
  onNavigate: () => void;
}) {
  const tile = RAIL_TILES[icon];
  return (
    <Link
      href={href}
      {...(collapsed ? { title: label } : {})}
      onClick={onNavigate}
      aria-label={label}
      {...(active ? { 'aria-current': 'page' as const } : {})}
      className={`${ROW} ${collapsed ? ROW_ROUND : ROW_WIDE} ${active ? ROW_ACTIVE : ROW_IDLE} text-left`}
    >
      <NavPendingIcon>
        {tile ? (
          <RailTile src={tile} />
        ) : (
          <RailIcon name={icon} active={active} color={ICON_IDLE} activeColor={ICON_ACTIVE} />
        )}
      </NavPendingIcon>
      {!collapsed && <span className="truncate">{label}</span>}
    </Link>
  );
}

export function HomeSidebar({
  current,
  onModeChange,
  userEmail,
  collapsed,
  onToggleCollapsed,
  onNavigateTo,
  mobileOpen = false,
  onMobileClose,
  treeSlotRef,
}: {
  /** The rail entry to mark as the current page. */
  current: RailPage;
  /** Only on screens that own the generation mode (the generation space and
      an open project): the Image entry becomes the switch back to "Générer". */
  onModeChange?: (mode: AppMode) => void;
  /** The account shown at the foot (free access has a placeholder one). */
  userEmail: string;
  /** Folded to icons only. Owned by AppChrome, remembered in a cookie. */
  collapsed: boolean;
  onToggleCollapsed: () => void;
  /** Told which entry was clicked, so it is marked before its page arrives. */
  onNavigateTo: (page: RailPage) => void;
  /** Below 900px the rail is a drawer, opened only by an open project for
      its render tree. */
  mobileOpen?: boolean;
  onMobileClose?: () => void;
  /** Present when the page has a render tree to show here. */
  treeSlotRef: ((el: HTMLElement | null) => void) | null;
}) {
  const t = useTranslations();
  const { logout, loggingOut } = useAuth();

  // No account (free-access mode) shows a neutral label. See lib/account-label.ts.
  const placeholder = isPlaceholderAccount(userEmail);
  const accountLabel = placeholder ? t('app.freeAccessAccount') : userEmail;
  const initial = accountLabel.trim().charAt(0).toUpperCase() || '?';
  // An open drawer means a narrow screen: the desktop fold must not apply —
  // a 76px drawer with no labels would be useless.
  const folded = mobileOpen ? false : collapsed;

  function link(href: string, label: string, icon: RailIconName, page: RailPage) {
    return (
      <RailLink
        href={href}
        label={label}
        icon={icon}
        active={current === page}
        collapsed={folded}
        onNavigate={() => {
          onNavigateTo(page);
          onMobileClose?.();
        }}
      />
    );
  }

  /** Caption: left-aligned when open, centred over the icons when folded. */
  function caption(label: string) {
    return (
      <p
        className={`${RAIL_CAPTION} mb-2 truncate ${folded ? 'px-1 text-center text-[11.5px]' : 'px-3'}`}
      >
        {label}
      </p>
    );
  }

  /** A foot row (assistant, sign out): same shape as a link. */
  const footRow = `${ROW} ${folded ? ROW_ROUND : ROW_WIDE} ${ROW_IDLE} w-full text-left`;
  const sectionPad = folded ? 'px-2 py-4' : 'px-4 py-4';

  async function handleLogout() {
    await logout();
    // Out of the site entirely, onto the landing (owner, 2026-10-08): a full
    // page load, not a client navigation, so nothing of the app survives.
    window.location.assign('/');
  }

  return (
    <aside
      // Below 900px an overlay drawer (`fixed`, off-canvas until opened);
      // from 900px a floating card on the grey ground, the full height.
      className={`${mobileOpen ? 'flex' : 'hidden'} fixed bottom-0 left-0 top-16 z-40 flex-col overflow-hidden bg-white shadow-[0_1px_2px_rgba(23,22,31,0.04)] transition-[width] duration-200 ease-out min-[900px]:static min-[900px]:z-auto min-[900px]:my-3 min-[900px]:ml-3 min-[900px]:flex min-[900px]:flex-shrink-0 min-[900px]:rounded-[20px] ${
        folded ? 'w-[76px]' : 'w-[264px]'
      }`}
    >
      {/* The fold button, then the RenderBox name (owner, 2026-10-08: the
          blue square mark gave way to the button; their own logo will sit
          beside the name). Folded, only the button is left. */}
      <div
        className={`flex h-[72px] flex-shrink-0 items-center ${folded ? 'justify-center' : 'gap-3 pl-4 pr-4'}`}
      >
        <button
          type="button"
          onClick={onToggleCollapsed}
          aria-label={folded ? t('app.sidebarExpand') : t('app.sidebarCollapse')}
          title={folded ? t('app.sidebarExpand') : t('app.sidebarCollapse')}
          className={`group ${RAIL_TOGGLE}`}
        >
          <PanelToggleIcon open={!folded} size={18} />
        </button>
        {!folded && (
          <Link href="/app" className="min-w-0">
            <span className="block truncate font-[family-name:var(--font-display)] text-[20px] font-bold text-[#2948FC]">
              RenderBox
            </span>
          </Link>
        )}
      </div>

      <div className="flex min-h-0 flex-1 flex-col overflow-y-auto overflow-x-hidden">
        <div className={`${SECTION} ${sectionPad}`}>
          {caption(t('app.railGroupGeneral'))}
          <nav className="flex flex-col gap-1">
            {link('/app', t('app.railHome'), 'dashboard', 'dashboard')}
            {link('/app/images', t('app.railImages'), 'projects', 'images')}
            {/* Where the page owns the generation mode, the Image entry is the
                switch back to "Générer"; everywhere else a link to that space. */}
            {onModeChange && current === 'generate' ? (
              <button
                type="button"
                onClick={() => {
                  onModeChange('generate');
                  onMobileClose?.();
                }}
                {...(folded ? { title: t('app.modeGenerate') } : {})}
                aria-label={t('app.modeGenerate')}
                aria-current="page"
                className={`${ROW} ${folded ? ROW_ROUND : ROW_WIDE} ${ROW_ACTIVE} text-left`}
              >
                <RailTile src="/rail/image.webp" />
                {!folded && <span>{t('app.modeGenerate')}</span>}
              </button>
            ) : (
              link('/app/generer', t('app.modeGenerate'), 'image', 'generate')
            )}
            {link('/app/enhance', t('app.railEnhance'), 'enhance', 'enhance')}
          </nav>
        </div>

        <div className={`${SECTION} ${sectionPad}`}>
          {caption(t('app.railGroupHelp'))}
          <nav className="flex flex-col gap-1">
            {/* /app/info, not /info: the public changelog wears the landing's
                header, and nothing inside the app may lead back there. */}
            {link('/app/info', t('app.railInfo'), 'info', 'info')}
            <button
              type="button"
              onClick={() => {
                onMobileClose?.();
                openAssistant();
              }}
              {...(folded ? { title: t('app.assistant') } : {})}
              aria-label={t('app.assistant')}
              className={footRow}
            >
              <RailTile src="/rail/assistant.webp" />
              {!folded && <span>{t('app.assistant')}</span>}
            </button>
          </nav>
        </div>

        {/* A project's render tree, portalled here by AppFrame. Only it
            scrolls, so the groups and the foot stay put. It needs its labels,
            so it goes when folded. */}
        {treeSlotRef && (
          <div
            ref={treeSlotRef}
            className={`${SECTION} min-h-0 flex-1 overflow-y-auto px-4 py-4 ${folded ? 'hidden' : ''}`}
          />
        )}

        <div className={`${SECTION} ${sectionPad} mt-auto`}>
          {caption(t('app.railGroupProfile'))}
          <nav className="flex flex-col gap-1">
            {link('/parametres', t('parametres.title'), 'settings', 'settings')}
            {link('/app/tarifs', t('app.railPricing'), 'pricing', 'pricing')}
            {/* Always Se déconnecter (owner, 2026-10-08: inside the app you
                are signed in). In free access there is no session to end:
                logout() clears nothing and the click lands on the landing. */}
            <button
              type="button"
              disabled={loggingOut}
              onClick={() => void handleLogout()}
              {...(folded ? { title: t('parametres.logoutButton') } : {})}
              aria-label={t('parametres.logoutButton')}
              className={`${footRow} disabled:opacity-60`}
            >
              <RailTile src="/rail/deconnexion.webp" />
              {!folded && <span>{t('parametres.logoutButton')}</span>}
            </button>
          </nav>
        </div>
      </div>

      {/* The account, as the reference closes its sidebar: initials, the name,
          a chevron. Opens Paramètres. */}
      <Link
        href="/parametres"
        onClick={() => {
          onNavigateTo('settings');
          onMobileClose?.();
        }}
        title={accountLabel}
        aria-label={accountLabel}
        className={`${SECTION} flex flex-shrink-0 items-center transition-colors hover:bg-[#FBFBFD] ${
          folded ? 'justify-center gap-0.5 px-2 py-4' : 'gap-3 px-5 py-4'
        }`}
      >
        <span className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-[#EEF1FF] text-[14px] font-semibold text-[#2948FC]">
          {initial}
        </span>
        {!folded && (
          <span className="flex min-w-0 flex-1 flex-col leading-tight">
            <span className="truncate text-[14px] font-semibold text-[#17161F]">
              {accountLabel}
            </span>
            <span className="truncate text-[12px] text-[#6B6878]">{t('app.railAccountSub')}</span>
          </span>
        )}
        <ChevronDown set="curved" size={folded ? 12 : 15} primaryColor="#6B6878" />
      </Link>
    </aside>
  );
}
