'use client';

// "Fonctionnalités clés" — one card per trade (four since 2026-10-07: architects,
// engineers & design offices, building draughtspeople, developers & builders).
//
// Reference layout (2026-10-05): a row of cards, the second one lifted out in
// the brand red (green until 2026-10-08, when the owner moved the site to red
// and blue; red is the accent). One highlighted card gives the row a focal
// point; it carries no state.
//
// 2026-10-08 — like the dashboard cards, no paragraph any more (owner: "éviter
// de mettre trop de texte"): the trade in small type, the title, and a 3D
// image of what the title says, generated by the owner, its ground melting
// into the card as on the dashboard (owner: "fais fondre le fond"): the grey
// studio grounds were lifted to pure white and the picture is multiplied onto
// the card, so white becomes the card's own grey; the red one was colour-matched
// to the card and its edges fade out. 4:3 WebP in /public/metiers.
import { Reveal } from './Reveal';

/** The lifted card: the brand red with its pink glow, as on the dashboard's red card. */
const LEAD =
  'bg-[radial-gradient(120%_90%_at_100%_0%,#F88B98_0%,rgba(248,139,152,0)_55%),linear-gradient(135deg,#F34857_0%,#EF3E50_60%,#E2364A_100%)]';

export interface AudienceCardData {
  /** Who this column is for — the small line above the title. */
  label: string;
  title: string;
  /** Path under /public of the card's picture. */
  image: string;
}

export function AudienceCards({ cards }: { cards: AudienceCardData[] }) {
  return (
    <div className="grid grid-cols-1 gap-5 min-[640px]:grid-cols-2 min-[1100px]:grid-cols-4">
      {cards.map((card, i) => {
        const lead = i === 1;
        return (
          <Reveal key={card.label} delayMs={i * 90} className="h-full">
            <div
              className={`group flex h-full flex-col rounded-[24px] p-3 text-center transition-transform duration-[250ms] ease-out motion-safe:hover:-translate-y-1 ${
                lead
                  ? `${LEAD} text-white shadow-[0_24px_48px_-24px_rgba(226,54,74,0.55)]`
                  : 'bg-[#F7F7FA]'
              }`}
            >
              <div className="flex flex-1 flex-col items-center justify-center px-4 pb-5 pt-6">
                <span
                  className={`mb-2 font-[family-name:var(--font-mono)] text-[11px] uppercase tracking-wide ${
                    lead ? 'text-white' : 'text-[#2948FC]'
                  }`}
                >
                  {card.label}
                </span>
                <h3
                  className={`text-[18px] font-semibold leading-[1.3] ${
                    lead ? 'text-white' : 'text-[#17161F]'
                  }`}
                >
                  {card.title}
                </h3>
              </div>
              <div>
                <img
                  src={card.image}
                  alt=""
                  aria-hidden
                  loading="lazy"
                  draggable={false}
                  className={`aspect-[4/3] w-full object-cover transition-transform duration-500 ease-out motion-safe:group-hover:scale-[1.04] ${lead ? '[mask-image:radial-gradient(ellipse_68%_62%_at_50%_40%,#000_52%,transparent_100%)]' : 'mix-blend-multiply [mask-image:linear-gradient(90deg,transparent_0%,#000_14%,#000_86%,transparent_100%)]'}`}
                />
              </div>
            </div>
          </Reveal>
        );
      })}
    </div>
  );
}
