'use client';

// The landing FAQ's illustration column (2026-10-08, owner: "à chaque clic il
// y a une image qui viendra pour mieux expliquer"). From 960px it sits under
// the section header, in the column that used to stay empty, and shows the
// picture of the question that is open — or of the last one opened, so the
// column never empties when a question is closed. All ten are stacked and
// cross-faded, so switching never waits on a download. Below 960px the
// accordion shows the picture inside the open answer instead.
//
// The pictures are soft 3D illustrations generated by the owner (one per
// question, no text in them so they serve both languages), 800px squares in
// public/faq/<n>.webp, numbered in the questions' order.
import { usePrefersReducedMotion } from './hooks/usePrefersReducedMotion';

export function FaqIllustration({ images, shown }: { images: string[]; shown: number }) {
  const reducedMotion = usePrefersReducedMotion();
  return (
    <div
      aria-hidden
      className="relative mt-8 hidden aspect-square w-full max-w-[420px] overflow-hidden rounded-[24px] bg-[#EEEDF2] shadow-[0_20px_44px_-28px_rgba(23,22,31,0.35)] min-[960px]:sticky min-[960px]:top-24 min-[960px]:block"
    >
      {images.map((src, i) => (
        <img
          key={src}
          src={src}
          alt=""
          loading="lazy"
          draggable={false}
          className={`absolute inset-0 h-full w-full object-cover ${
            reducedMotion
              ? ''
              : 'transition-[opacity,scale] duration-500 ease-[cubic-bezier(0.16,1,0.3,1)]'
          } ${i === shown ? 'scale-100 opacity-100' : 'scale-[1.03] opacity-0'}`}
        />
      ))}
    </div>
  );
}
